### ISSUE TITLE
config.ini.php could not be read

### ISSUE THREAD

**Issue by RetroGameTalk** [matomo-org/matomo-log-analytics#297]
This must be something silly but, i have no idea why it can't do it:
![why](https://user-images.githubusercontent.com/8179611/103214822-d6167600-4911-11eb-8fd2-220f4c52dded.png)

What could i try?

**Comment by RetroGameTalk** [comment]
The whole importing logs is very frustrating for me why can't i upload a log file to your web interface?
It requires a local copy to import logs.
A local copy was what i was trying to avoid in the first place.

**Comment by Findus23** [comment]
Hi,

Can you check that `/var/www/matomo/config/config.ini.php` does exist? Are you running the python script on the same server as the Matomo setup?

If you are running the script on another server you need to add `-token-auth=` with an API token that has write permission, so that the script is allowed to import arbitrary data.

> The whole importing logs is very frustrating for me why can't i upload a log file to your web interface?

The point of log-analytics is that you can automate this part and don't have to do any manual steps after the setup.
